-d Z:\FPGA\projects\adder\impl\gwsynthesis\adder.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst Z:\FPGA\projects\adder\src\adder.cst
-cfg Z:\FPGA\projects\adder\impl\pnr\device.cfg
-sdc Z:\FPGA\projects\adder\src\adder.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
