-d Z:\FPGA\projects\led\impl\gwsynthesis\led.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst Z:\FPGA\projects\led\src\led.cst
-cfg Z:\FPGA\projects\led\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
